name: cicd

on:
  push:
    branches:
      - main

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jiridj/wm-apigw-actions-register-api@v1
        with: 
          apigw-url: ${{ secrets.APIGW_URL }}
          apigw-username: ${{ secrets.APIGW_USERNAME }}
          apigw-password: ${{ secrets.APIGW_PASSWORD }}
          api-spec: openapi.json
          set-active: true
          debug: ${{ secrets.ACTIONS_STEP_DEBUG }}
  
  integration-tests:
    needs: [ deploy-test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: run pet management tests
        env:
          collectionId: 19018100-f1a69c50-8013-4cde-83d9-c6d51932bb92
        run: newman run "https://api.getpostman.com/collections/${collectionId}?apikey=${{secrets.POSTMAN_API_KEY}}" -r htmlextra
      - name: run user management tests
        env:
          collectionId: 19018100-deb57317-4821-47ec-bba2-f81b8ef3449d
        run: newman run "https://api.getpostman.com/collections/${collectionId}?apikey=${{secrets.POSTMAN_API_KEY}}" -r htmlextra
      - uses: actions/upload-artifact@v3
        with:
          name: integration-tests
          path: newman